import type {
  Asset,
  AuditEvent,
  LicenseAllocation,
  LicenseEntitlement,
  NotificationItem,
  Site,
  SoftwareProduct,
  UserAccount,
} from "./types";
import { deriveEntitlement } from "./license-derived";

export const sites: Site[] = [
  { id: "factory", name: "TKC Factory", shortName: "Factory" },
  { id: "bangkok-office", name: "Bangkok Office", shortName: "Office" },
];

const factory = sites[0];
const office = sites[1];

const assetInputs: Array<Omit<Asset, "version">> = [
  {
    id: "tpo-083",
    assetCode: "TPO-083",
    computerName: "TPO-083-PC",
    type: "pc",
    status: "active",
    site: factory,
    location: "Power Room",
    department: "POWER",
    primaryUser: "Sompop",
    responsiblePerson: "Panuwat",
    manufacturer: "Dell",
    model: "OptiPlex 7010",
    purchaseDate: "2024-02-12",
    operatingSystem: "Windows 11 Professional",
    internetLevel: "Level 1",
    networkInterfaces: [
      { id: "nic-tpo083-lan", type: "lan", macAddress: "74:56:3C:9F:F1:4B", ipAddress: "192.168.1.57", vlan: "VLAN 1" },
    ],
  },
  {
    id: "twe-096",
    assetCode: "TWE-096",
    computerName: "TWE-096-NB",
    type: "notebook",
    status: "active",
    site: factory,
    location: "Chosa Room",
    department: "WEAVING",
    primaryUser: "Phinitnan",
    responsiblePerson: "Phinitnan",
    manufacturer: "Lenovo",
    model: "ThinkPad E14",
    purchaseDate: "2025-05-20",
    operatingSystem: "Windows 11 Professional",
    internetLevel: "Level 2",
    networkInterfaces: [
      { id: "nic-twe096-lan", type: "lan", macAddress: "F0:9E:4A:82:2B:84", ipAddress: "192.168.1.55", vlan: "VLAN 1" },
      { id: "nic-twe096-wifi", type: "wifi", macAddress: "F0:9E:4A:82:2B:85", ipAddress: "DHCP" },
    ],
  },
  {
    id: "tpo-069",
    assetCode: "TPO-069",
    computerName: "TPO-069-PC",
    type: "pc",
    status: "active",
    site: factory,
    location: "Power Room",
    department: "POWER",
    primaryUser: "Techin",
    responsiblePerson: "Techin",
    manufacturer: "HP",
    model: "ProDesk 400",
    operatingSystem: "Windows 11 Professional",
    internetLevel: "Level 1",
    networkInterfaces: [
      { id: "nic-tpo069-lan", type: "lan", macAddress: "74:56:3C:9F:74:14", ipAddress: "192.168.1.142", vlan: "VLAN 1" },
    ],
  },
  {
    id: "scan01",
    assetCode: "TWE-095",
    computerName: "SCAN01",
    type: "pc",
    status: "repair",
    site: factory,
    location: "Chosa Room",
    department: "WEAVING",
    primaryUser: "ITTCS",
    responsiblePerson: "Phinitnan",
    manufacturer: "Custom",
    model: "Industrial PC",
    operatingSystem: "Windows 10 Professional",
    internetLevel: "Level 2",
    networkInterfaces: [
      { id: "nic-scan01-lan", type: "lan", macAddress: "00:0A:CD:35:B3:B1", ipAddress: "192.168.1.20", vlan: "VLAN 1" },
    ],
    remark: "อยู่ระหว่างตรวจสอบการเชื่อมต่อกับเครื่องจักร",
  },
  {
    id: "thai-kurabo-server",
    assetCode: "TKC-SRV-001",
    computerName: "THAI-KURABO",
    type: "server",
    status: "active",
    site: office,
    location: "Server Room",
    department: "ADMIN",
    primaryUser: "Administrator",
    responsiblePerson: "IT Department",
    manufacturer: "HPE",
    model: "ProLiant ML30",
    purchaseDate: "2023-01-18",
    operatingSystem: "Windows Server 2022",
    internetLevel: "Internal",
    networkInterfaces: [
      { id: "nic-srv01-lan", type: "lan", macAddress: "28:92:4A:2D:EC:1D", ipAddress: "192.168.0.254", vlan: "SERVER" },
    ],
  },
  {
    id: "tkcbkklt001",
    assetCode: "TKCBKKLT001",
    computerName: "TKCBKKLT001",
    type: "notebook",
    status: "active",
    site: office,
    location: "Bangkok Office",
    department: "OFFICE",
    primaryUser: "Moriwake",
    responsiblePerson: "Admin Team",
    manufacturer: "Fujitsu",
    model: "LIFEBOOK U7412",
    purchaseDate: "2022-09-10",
    operatingSystem: "Windows 10 Professional",
    internetLevel: "Standard",
    networkInterfaces: [
      { id: "nic-lt001-wifi", type: "wifi", macAddress: "AC:12:03:18:21:9E", ipAddress: "DHCP", vlan: "OFFICE" },
    ],
  },
  {
    id: "tkcbkklt002",
    assetCode: "TKCBKKLT002",
    computerName: "TKCBKKLT002",
    type: "notebook",
    status: "active",
    site: office,
    location: "Bangkok Office",
    department: "OFFICE",
    primaryUser: "Supachai",
    responsiblePerson: "Admin Team",
    manufacturer: "Panasonic",
    model: "Let's Note",
    operatingSystem: "Windows 10 Professional",
    internetLevel: "Standard",
    networkInterfaces: [
      { id: "nic-lt002-wifi", type: "wifi", macAddress: "E8:2A:44:9C:2F:71", ipAddress: "DHCP", vlan: "OFFICE" },
    ],
  },
  {
    id: "tkcbkklt014",
    assetCode: "TKCBKKLT014",
    computerName: "TKCBKKLT014",
    type: "notebook",
    status: "spare",
    site: office,
    location: "Bangkok Office",
    department: "OFFICE",
    primaryUser: "Spare",
    responsiblePerson: "Admin Team",
    manufacturer: "HP",
    model: "EliteBook 640",
    operatingSystem: "Windows 10 Professional",
    internetLevel: "Standard",
    networkInterfaces: [{ id: "nic-lt014-wifi", type: "wifi", ipAddress: "DHCP", vlan: "OFFICE" }],
  },
];

export const assets: Asset[] = assetInputs.map((asset) => ({ ...asset, version: 1 }));

const productInputs: Array<Omit<SoftwareProduct, "versionNumber">> = [
  { id: "windows-11-pro", publisher: "Microsoft", name: "Windows", version: "11 Professional", category: "Operating System", active: true },
  { id: "windows-10-pro", publisher: "Microsoft", name: "Windows", version: "10 Professional", category: "Operating System", active: true },
  { id: "windows-server-2022", publisher: "Microsoft", name: "Windows Server", version: "2022 Standard", category: "Operating System", active: true },
  { id: "office-365-family", publisher: "Microsoft", name: "Office 365 Family", version: "Subscription", category: "Office", active: true },
  { id: "office-2016-standard", publisher: "Microsoft", name: "Office Standard", version: "2016", category: "Office", active: true },
  { id: "sql-server-2019", publisher: "Microsoft", name: "SQL Server Standard", version: "2019", category: "Database", active: true },
  { id: "autocad-2014", publisher: "Autodesk", name: "AutoCAD", version: "2014", category: "CAD", active: true },
  { id: "winrar-38", publisher: "win.rar GmbH", name: "WinRAR", version: "3.8", category: "Utility", active: false },
];

export const products: SoftwareProduct[] = productInputs.map((product) => ({ ...product, versionNumber: 1 }));

const licenseInputs: Array<Omit<LicenseEntitlement, "allocatedQuantity" | "availableQuantity" | "complianceStatus" | "lifecycleStatus" | "version">> = [
  {
    id: "lic-windows-11-factory",
    reference: "LIC-FAC-2025-001",
    product: products[0],
    vendor: "Nine System Integrator Co., Ltd.",
    classification: "Regular version",
    purchaseForm: "Volume License",
    ownedQuantity: 120,
    licenseKeyMasked: "****-MASKED",
    serialNumberMasked: "****-MASKED",
    purchaseDate: "2025-01-15",
    startDate: "2025-01-15",
    siteScope: "Factory",
    owner: "Thai Kurabo",
  },
  {
    id: "lic-windows-10-office",
    reference: "LIC-OFF-2020-004",
    product: products[1],
    vendor: "Reunion Solution Co., Ltd.",
    classification: "Regular version",
    purchaseForm: "Volume License",
    ownedQuantity: 40,
    licenseKeyMasked: "****-MASKED",
    serialNumberMasked: "****-MASKED",
    purchaseDate: "2020-01-22",
    startDate: "2020-01-22",
    siteScope: "Bangkok Office",
    owner: "Thai Kurabo",
  },
  {
    id: "lic-server-2022",
    reference: "LIC-OFF-2023-001",
    product: products[2],
    vendor: "Enterprise Systems Thailand",
    classification: "OEM",
    purchaseForm: "Package",
    ownedQuantity: 1,
    licenseKeyMasked: "****-MASKED",
    serialNumberMasked: "****-MASKED",
    purchaseDate: "2023-01-18",
    startDate: "2023-01-18",
    siteScope: "Bangkok Office",
    owner: "Thai Kurabo",
  },
  {
    id: "lic-office-365",
    reference: "SUB-2026-0365",
    product: products[3],
    vendor: "Microsoft CSP Partner",
    classification: "Subscription",
    purchaseForm: "Cloud Subscription",
    ownedQuantity: 33,
    licenseKeyMasked: "****-MASKED",
    serialNumberMasked: "****-MASKED",
    purchaseDate: "2025-10-01",
    startDate: "2025-10-01",
    endDate: "2026-10-01",
    siteScope: "All Sites",
    owner: "Thai Kurabo",
  },
  {
    id: "lic-office-2016-factory",
    reference: "LIC-FAC-2016-078",
    product: products[4],
    vendor: "MIRA Computer International",
    classification: "Regular version",
    purchaseForm: "License",
    ownedQuantity: 78,
    licenseKeyMasked: "****-MASKED",
    serialNumberMasked: "****-MASKED",
    purchaseDate: "2016-08-28",
    startDate: "2016-08-28",
    siteScope: "Factory",
    owner: "Thai Kurabo",
  },
  {
    id: "lic-sql-2019",
    reference: "LIC-FAC-2019-SQL",
    product: products[5],
    vendor: "Control-A Solutions Co., Ltd.",
    classification: "Regular version",
    purchaseForm: "License",
    ownedQuantity: 1,
    licenseKeyMasked: "****-MASKED",
    serialNumberMasked: "****-MASKED",
    purchaseDate: "2019-11-11",
    startDate: "2019-11-11",
    siteScope: "Factory",
    owner: "Thai Kurabo",
    remark: "ต้องตรวจสอบสิทธิ์เพิ่มเติม 1 seat",
  },
  {
    id: "lic-autocad-2014",
    reference: "LIC-FAC-2014-CAD",
    product: products[6],
    vendor: "Authorized Autodesk Partner",
    classification: "Perpetual",
    purchaseForm: "License",
    ownedQuantity: 4,
    licenseKeyMasked: "****-MASKED",
    serialNumberMasked: "****-MASKED",
    purchaseDate: "2014-04-01",
    siteScope: "Factory",
    owner: "Thai Kurabo",
  },
  {
    id: "lic-winrar-legacy",
    reference: "LIC-FAC-2009-WR",
    product: products[7],
    vendor: "MIRA Computer International",
    classification: "Regular version",
    purchaseForm: "License",
    ownedQuantity: 43,
    licenseKeyMasked: "****-MASKED",
    serialNumberMasked: "****-MASKED",
    purchaseDate: "2009-04-22",
    endDate: "2015-04-22",
    siteScope: "Factory",
    owner: "Thai Kurabo",
  },
];

const allocationInputs: Array<Omit<LicenseAllocation, "version">> = [
  { id: "alloc-001", licenseId: "lic-windows-11-factory", productName: "Windows 11 Professional", targetType: "asset", targetId: "tpo-083", targetName: "TPO-083-PC", site: factory, quantity: 1, allocatedAt: "2025-01-16", status: "active" },
  { id: "alloc-002", licenseId: "lic-windows-11-factory", productName: "Windows 11 Professional", targetType: "asset", targetId: "twe-096", targetName: "TWE-096-NB", site: factory, quantity: 1, allocatedAt: "2025-05-21", status: "active" },
  { id: "alloc-003", licenseId: "lic-windows-10-office", productName: "Windows 10 Professional", targetType: "asset", targetId: "tkcbkklt001", targetName: "TKCBKKLT001", site: office, quantity: 1, allocatedAt: "2020-01-22", status: "active" },
  { id: "alloc-004", licenseId: "lic-server-2022", productName: "Windows Server 2022 Standard", targetType: "asset", targetId: "thai-kurabo-server", targetName: "THAI-KURABO", site: office, quantity: 1, allocatedAt: "2023-01-18", status: "active" },
  { id: "alloc-005", licenseId: "lic-office-365", productName: "Office 365 Family", targetType: "person", targetId: "user-supachai", targetName: "Supachai", site: office, quantity: 1, allocatedAt: "2025-10-01", status: "active" },
  { id: "alloc-006", licenseId: "lic-autocad-2014", productName: "AutoCAD 2014", targetType: "asset", targetId: "tpo-069", targetName: "TPO-069-PC", site: factory, quantity: 1, allocatedAt: "2019-04-01", status: "active" },
{ id: "alloc-base-w11", licenseId: "lic-windows-11-factory", productName: "Windows 11 Professional", targetType: "site", targetId: "baseline-factory", targetName: "Imported baseline (Factory)", site: factory, quantity: 102, allocatedAt: "2026-08-28", status: "active", remark: "จำนวนสรุปจาก Excel สำหรับ migration รอบแรก" },
  { id: "alloc-base-w10", licenseId: "lic-windows-10-office", productName: "Windows 10 Professional", targetType: "site", targetId: "baseline-office", targetName: "Imported baseline (Office)", site: office, quantity: 34, allocatedAt: "2026-08-28", status: "active", remark: "จำนวนสรุปจาก Excel สำหรับ migration รอบแรก" },
  { id: "alloc-base-o365", licenseId: "lic-office-365", productName: "Office 365 Family", targetType: "site", targetId: "baseline-all", targetName: "Imported baseline (All Sites)", site: office, quantity: 29, allocatedAt: "2026-08-28", status: "active", remark: "จำนวนสรุปจาก Excel สำหรับ migration รอบแรก" },
  { id: "alloc-base-o16", licenseId: "lic-office-2016-factory", productName: "Office Standard 2016", targetType: "site", targetId: "baseline-factory", targetName: "Imported baseline (Factory)", site: factory, quantity: 78, allocatedAt: "2026-08-28", status: "active", remark: "จำนวนสรุปจาก Excel สำหรับ migration รอบแรก" },
  { id: "alloc-base-sql", licenseId: "lic-sql-2019", productName: "SQL Server Standard 2019", targetType: "site", targetId: "baseline-factory", targetName: "Imported baseline (Factory)", site: factory, quantity: 2, allocatedAt: "2026-08-28", status: "active", remark: "จำนวนสรุปจาก Excel สำหรับ migration รอบแรก" },
  { id: "alloc-base-cad", licenseId: "lic-autocad-2014", productName: "AutoCAD 2014", targetType: "site", targetId: "baseline-factory", targetName: "Imported baseline (Factory)", site: factory, quantity: 3, allocatedAt: "2026-08-28", status: "active", remark: "จำนวนสรุปจาก Excel สำหรับ migration รอบแรก" },
  { id: "alloc-base-winrar", licenseId: "lic-winrar-legacy", productName: "WinRAR 3.8", targetType: "site", targetId: "baseline-factory", targetName: "Imported baseline (Factory)", site: factory, quantity: 40, allocatedAt: "2026-08-28", status: "active", remark: "จำนวนสรุปจาก Excel สำหรับ migration รอบแรก" },
];

export const allocations: LicenseAllocation[] = allocationInputs.map((allocation) => ({ ...allocation, version: 1 }));

export const licenses: LicenseEntitlement[] = licenseInputs.map((license) =>
  deriveEntitlement({ ...license, version: 1 }, allocations),
);

const notificationInputs: Array<Omit<NotificationItem, "dismissed">> = [
  { id: "notice-001", title: "Office 365 ใกล้หมดอายุ", message: "Subscription จำนวน 33 seats จะหมดอายุภายใน 30 วัน", severity: "warning", entityType: "license", entityId: "lic-office-365", createdAt: "2026-09-01T08:30:00Z", read: false },
  { id: "notice-002", title: "SQL Server ใช้เกินสิทธิ์", message: "จัดสรร 2 seats จากสิทธิ์ที่มี 1 seat", severity: "critical", entityType: "license", entityId: "lic-sql-2019", createdAt: "2026-09-01T07:15:00Z", read: false },
  { id: "notice-003", title: "WinRAR License หมดอายุ", message: "License รุ่นเดิมหมดอายุและควรตรวจแผนทดแทน", severity: "critical", entityType: "license", entityId: "lic-winrar-legacy", createdAt: "2026-08-31T04:10:00Z", read: true },
  { id: "notice-004", title: "Asset รอการตรวจสอบ", message: "SCAN01 มีสถานะ Repair และข้อมูล Network ต้องยืนยัน", severity: "info", entityType: "asset", entityId: "scan01", createdAt: "2026-08-30T09:45:00Z", read: true },
];

export const notifications: NotificationItem[] = notificationInputs.map((notification) => ({ ...notification, dismissed: false }));

export const auditEvents: AuditEvent[] = [
  { id: "audit-001", action: "update", entityType: "Asset", entityId: "tpo-083", description: "อัปเดต IP Address และ VLAN", actor: "Admin User", occurredAt: "2026-09-01T09:10:00Z" },
  { id: "audit-002", action: "allocate", entityType: "License", entityId: "lic-office-365", description: "จัดสรร Office 365 ให้ Supachai", actor: "Admin User", occurredAt: "2026-08-31T10:30:00Z" },
  { id: "audit-003", action: "export", entityType: "Report", entityId: "license-compliance", description: "Export รายงาน License Compliance", actor: "IT Manager", occurredAt: "2026-08-30T03:15:00Z" },
  { id: "audit-004", action: "reveal-secret", entityType: "License", entityId: "lic-server-2022", description: "เปิดดู License Key ฉบับเต็ม", actor: "Admin User", occurredAt: "2026-08-29T08:05:00Z" },
];

const userAccountInputs: Array<Omit<UserAccount, "version">> = [
  { id: "user-admin", name: "Admin User", email: "admin@thaikurabo.example", role: "admin", status: "active", lastLoginAt: "2026-09-01T09:00:00Z" },
  { id: "user-it-manager", name: "IT Manager", email: "it.manager@thaikurabo.example", role: "admin", status: "active", lastLoginAt: "2026-09-01T08:40:00Z" },
  { id: "user-viewer", name: "Report Viewer", email: "viewer@thaikurabo.example", role: "user", status: "active", lastLoginAt: "2026-08-31T06:20:00Z" },
  { id: "user-auditor", name: "Internal Auditor", email: "audit@thaikurabo.example", role: "user", status: "inactive", lastLoginAt: "2026-07-15T04:00:00Z" },
];

export const userAccounts: UserAccount[] = userAccountInputs.map((user) => ({ ...user, version: 1 }));
