"use client";

import Link from "next/link";
import { ArrowLeft, KeyRound, PackageCheck, ShieldCheck, Users } from "lucide-react";
import type { LicenseAllocation, LicenseEntitlement, Role } from "@/features/sam/types";
import { formatDate, formatNumber } from "@/features/sam/formatters";
import { StatusBadge } from "@/components/ui/status-badge";
import { LicenseKey } from "./license-key";

export function LicenseDetail({ license, allocations, role }: { license: LicenseEntitlement; allocations: LicenseAllocation[]; role: Role }) {
  return <div className="mx-auto max-w-[1500px] space-y-6"><Link href="/licenses" className="inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-slate-600 hover:text-blue-700"><ArrowLeft aria-hidden="true" size={17} />กลับไปหน้า Licenses</Link><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div className="flex gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-blue-50 text-blue-700"><KeyRound aria-hidden="true" size={25} /></span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-slate-950">{license.product.name}</h1><StatusBadge status={license.lifecycleStatus} /></div><p className="mt-1 text-sm text-slate-500">{license.product.version} · {license.reference}</p></div></div><StatusBadge status={license.complianceStatus} /></div></section><div className="grid gap-4 sm:grid-cols-3"><Metric label="Owned" value={license.ownedQuantity} icon={PackageCheck} /><Metric label="Allocated" value={license.allocatedQuantity} icon={Users} /><Metric label="Available" value={license.availableQuantity} icon={ShieldCheck} /></div><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-950">License information</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="Publisher" value={license.product.publisher} /><Info label="Vendor" value={license.vendor} /><Info label="Site scope" value={license.siteScope} /><Info label="Purchase form" value={license.purchaseForm} /><Info label="Purchase date" value={formatDate(license.purchaseDate)} /><Info label="End date" value={formatDate(license.endDate)} /></dl><div className="mt-6 grid gap-5 border-t border-slate-100 pt-5 sm:grid-cols-2"><div><p className="mb-2 text-xs font-semibold text-slate-500">License Key</p><LicenseKey value={license.licenseKey} role={role} /></div><div><p className="mb-2 text-xs font-semibold text-slate-500">Serial Number</p><LicenseKey value={license.serialNumber} role={role} label="Serial Number" /></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-950">Active allocations</h2><div className="mt-4 space-y-3">{allocations.length ? allocations.map((item) => <article key={item.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><div><p className="font-bold text-slate-900">{item.targetName}</p><p className="mt-1 text-xs text-slate-500">{item.targetType} · {item.site.shortName}</p></div><span className="text-sm font-bold text-blue-700">{item.quantity} seat</span></article>) : <p className="py-12 text-center text-sm text-slate-500">ยังไม่มี Allocation</p>}</div></section></div></div>;
}
function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Users }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-950">{formatNumber(value)}</p></div><Icon aria-hidden="true" className="text-blue-600" size={24} /></div></article>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{value}</dd></div>; }

